version: "3.1"

services:
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test-db
      MYSQL_USER: db-user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
